name: vibe
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - attrs==24.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - bokeh==3.6.2
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorcet==3.1.0
      - contourpy==1.3.1
      - cucim-cu12==24.12.0
      - cuda-python==12.6.0
      - cudf-cu12==24.12.0
      - cugraph-cu12==24.12.0
      - cuml-cu12==24.12.0
      - cuproj-cu12==24.12.0
      - cupy-cuda12x==13.3.0
      - cuspatial-cu12==24.12.0
      - cuvs-cu12==24.12.0
      - cuxfilter-cu12==24.12.0
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-cuda==24.12.0
      - dask-cudf-cu12==24.12.0
      - dask-expr==1.1.19
      - datashader==0.16.3
      - defusedxml==0.7.1
      - distributed==2024.11.2
      - distributed-ucxx-cu12==0.41.0
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - filelock==3.16.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - geopandas==1.0.1
      - holoviews==1.20.0
      - huggingface-hub==0.27.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - isoduration==20.11.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-server==2.15.0
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libcudf-cu12==24.12.0
      - libcuspatial-cu12==24.12.0
      - libkvikio-cu12==24.12.1
      - libucx-cu12==1.17.0.post1
      - libucxx-cu12==0.41.0
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - locket==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.4.2
      - numba==0.60.0
      - numba-cuda==0.0.17.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvcomp-cu12==4.1.0.6
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvtx==0.2.10
      - nx-cugraph-cu12==24.12.0
      - omegaconf==2.3.0
      - open-clip-torch==2.29.0
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - panel==1.5.5
      - param==2.2.0
      - partd==1.4.2
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - propcache==0.2.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pyarrow==18.1.0
      - pycparser==2.22
      - pyct==0.5.0
      - pygments==2.18.0
      - pylibcudf-cu12==24.12.0
      - pylibcugraph-cu12==24.12.0
      - pylibraft-cu12==24.12.0
      - pynvjitlink-cu12==0.4.0
      - pynvml==11.4.1
      - pyogrio==0.10.0
      - pyparsing==3.2.1
      - pyproj==3.7.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pyviz-comms==3.0.3
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - raft-dask-cu12==24.12.0
      - rapids-dask-dependency==24.12.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rmm-cu12==24.12.1
      - rpds-py==0.22.3
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scipy==1.14.1
      - send2trash==1.8.3
      - shapely==2.0.6
      - simpervisor==1.0.0
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sympy==1.13.1
      - tblib==3.0.0
      - terminado==0.18.1
      - tifffile==2024.12.12
      - timm==1.0.12
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treelite==4.3.0
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - ucx-py-cu12==0.41.0
      - ucxx-cu12==0.41.0
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xarray==2024.11.0
      - xyzservices==2024.9.0
      - yarl==1.18.3
      - zict==3.0.0
      - zipp==3.21.0
