name: labelconsistent
target_label: 0
poisoning_rate: 0.25
benign_model_path: ...  # used for adversarial perturbations (todo move checkpoint to poisoned data)
eps: 16
alpha: 1.5
max_pixel: 255
steps: 30
device: cuda
clean_label: True